version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: swiftcodes
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app-local:
    build: .
    container_name: swift-codes-api-local
    depends_on:
      - postgres
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - "8081:8080"

  app:
    image: cebix90/swift-codes-api:latest
    container_name: swift-codes-api
    depends_on:
      - postgres
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - "8080:8080"

volumes:
  postgres_data: