name: Build and Push Docker Image

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # 3. Build backend jar
      - name: Build the backend application
        run: |
          chmod +x mvnw
          ./mvnw clean package -DskipTests

      # 4. Install Docker Compose (optional if Actions runner doesn't have it)
      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.22.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      # 5. Run docker-compose to test integration (optional step but useful)
      - name: Run docker-compose for integration test
        run: |
          docker-compose -f docker-compose.yml up -d --build
          echo "Waiting for backend to be healthy..."
          sleep 20
          curl --fail http://localhost:8080/api/swift-codes || exit 1
          docker-compose -f docker-compose.yml down

      # 6. Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 7. Build and push backend image
      - name: Build and push backend image
        run: |
          docker build -t cebix90/swift-codes-api:latest .
          docker push cebix90/swift-codes-api:latest