name: Build and Push Docker Image

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: swiftcodes
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Grant execute permission for Maven Wrapper
        run: chmod +x mvnw

      - name: Build jar with Maven
        run: ./mvnw clean package -DskipTests

      - name: Build Docker image
        run: docker build -t cebix90/swift-codes-api:latest .

      - name: Test Docker image locally (dry-run)
        run: docker run --rm -e SPRING_PROFILES_ACTIVE=docker cebix90/swift-codes-api:latest java -version

      - name: Exit if pull request (skip push to Docker Hub)
        if: github.event_name == 'pull_request'
        run: echo "PR build complete, skipping Docker Hub push."

      - name: Log in to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        if: github.event_name != 'pull_request'
        run: docker push cebix90/swift-codes-api:latest
