name: Build and Push Docker Image

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build the backend application
        run: |
          chmod +x mvnw
          ./mvnw clean package -DskipTests

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.22.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      - name: Run docker-compose for integration test
        run: |
          docker-compose -f docker-compose.yml up -d --build
          echo "Waiting for backend to start..."
          sleep 20
          docker-compose ps
          docker logs $(docker ps -qf "name=swift-codes-api") || true
          curl -v http://localhost:8080/v1/swift-codes/country/AW || exit 1
          docker-compose -f docker-compose.yml down

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push backend image
        run: |
          docker build -t cebix90/swift-codes-api:latest .
          docker push cebix90/swift-codes-api:latest